[package]
authors = ["Sergey Sova <mail@sergeysova.com>"]
edition = "2018"
name = "cardbox-api-internal"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-http = {version = "1.0.1", features = ["failure"]}
actix-rt = "1.1.1"
actix-swagger = "0.2.1"
actix-web = "2.0.0"
async-trait = "0.1.40"
awc = {version = "1.0.1", features = ["compress", "openssl"]}
cardbox-core = {path = "../core"}
cardbox-db = {path = "../db"}
cardbox-generator = {path = "../generator"}
chrono = {version = "0.4.15", features = ["serde"]}
dotenv = "0.15.0"
futures = "0.3.1"
lazy_static = "1.4.0"
log = "0.4.11"
openssl = "0.10.30"
pretty_env_logger = "0.4.0"
serde = {version = "1.0.115", features = ["derive"]}
serde_json = "1.0.57"
serde_plain = "0.3.0"
time = "0.1.43"
tokio = {version = "0.2.22", features = ["sync"]}
url = "2.1.1"
uuid = {version = "0.8.1", features = ["serde", "v4"]}
